github:
  prebuilds:
    master: true
    branches: false
    pullRequests: true
    pullRequestsFromForks: true
    addComment: true
    addBadge: true
    addLabel: prebuilt-in-gitpod
ports:
  - port: 5000
tasks:
  - init: pip3 install -r requirements.txt
    command: gp open main.py
vscode:
  extensions:
    - eamodio.gitlens@10.2.0:GNDO73Cmp0fYDiLNxVkbsQ==
    - esbenp.prettier-vscode@2.3.0:1F0Pvb/ORZ/T+b60LIMs8w==
    - humao.rest-client@0.23.0:JNawNa9Juht3Bl5xY2refg==
